#jms_security_extra:
#    secure_all_services: false
 #   expressions: true

security:
    encoders:
        Ethergroups\MainBundle\Entity\User: plaintext
        Symfony\Component\Security\Core\User\User: plaintext
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        ldapdatabase:
            id: ldap_user_provider
        in_memory:
            memory:
                users:
                    %admin_login%: { password: %admin_pass%, roles: 'ROLE_ADMIN' }
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        admin:
            pattern:  ^/admin
            security: true
            http_digest:
                realm: "Admin area"
                key: "Aw3s0meKEEYYYY!!!!!"
            provider:  in_memory
            
        login:
            pattern:  ^/login$
            security: false
            
        language:
            pattern:  ^/changeLanguage$
            security: false

        secured_area:
            pattern:   ^/
            #pattern:  ^/(.*/|login_check$|logout$)
            #pattern:  ^/(login_check$|logout$)
            security: true
            provider: ldapdatabase
            ldap: true

            # Do we need this?
            #form_login:
            #    check_path: /demo/secured/login_check
            #    login_path: /demo/secured/login
            
            logout:
                path:   /logout
                target: /
                
            # Do we need this?
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
