login:
    pattern:  /login
    defaults: { _controller: HUBerlinEPLiteProBundle:Security:login }

login_check:
    pattern:   /login_check
    
logout:
    pattern:   /logout
    
base:
    pattern:   /
    defaults: { _controller: HUBerlinEPLiteProBundle:Default:index }
    
group:
    pattern:   /group/{id}
    defaults: { _controller: HUBerlinEPLiteProBundle:Default:group, id: 0 }
    
group_delete:
    pattern:  /group/delete/{id}
    defaults: { _controller: HUBerlinEPLiteProBundle:Default:deleteGroup, id: 0 }
    
pad:
    pattern:   /pad/{padid}
    defaults:  { _controller: HUBerlinEPLiteProBundle:Default:pad, padid: 0 }
    