login:
    pattern:  /login
    defaults: { _controller: HUBerlinEPLiteProBundle:Security:login }

login_check:
    pattern:   /login_check
    
logout:
    pattern:   /logout
    
hu_base:
    pattern:   /
    defaults: { _controller: HUBerlinEPLiteProBundle:Default:index }
    
hu_group:
    pattern:   /group/{id}
    defaults: { _controller: HUBerlinEPLiteProBundle:Default:group, id: 0 }
    
hu_pad:
    pattern:   /pad/{padid}
    defaults:  { _controller: HUBerlinEPLiteProBundle:Default:pad, padid: 0 }
    