login:
    pattern:  /login
    defaults: { _controller: HUBerlinEPLiteProBundle:Security:login }

login_check:
    pattern:   /login_check
    
logout:
    pattern:   /logout
    
base:
    pattern:   /
    defaults: { _controller: HUBerlinEPLiteProBundle:Default:index }
    
group:
    pattern:   /group/{id}
    defaults: { _controller: HUBerlinEPLiteProBundle:Default:group, id: 0 }
    
group_delete:
    pattern:  /group/delete/{id}
    defaults: { _controller: HUBerlinEPLiteProBundle:Default:deleteGroup, id: 0 }
    
group_addUser:
    pattern:    /group/add/user/{id}
    defaults:   { _controller: HUBerlinEPLiteProBundle:Default:addUser, id: 0 }

group_addPicture:
    pattern:    /group/add/picture/{id}
    defaults:   { _controller: HUBerlinEPLiteProBundle:Default:addPicture, id: 0  }
    
group_removePicture:
    pattern:    /group/remove/picture/{id}
    defaults:   { _controller: HUBerlinEPLiteProBundle:Default:removePicture, id: 0  }
    
pad:
    pattern:   /pad/{padid}
    defaults:  { _controller: HUBerlinEPLiteProBundle:Default:pad, padid: 0 }
    
pad_delete:
    pattern:   /pad/delete/{padid}
    defaults:  { _controller: HUBerlinEPLiteProBundle:Default:deletePad, padid: 0 }
    
pad_switchPublic:
    pattern:    /pad/switch/{padid}
    defaults:  { _controller: HUBerlinEPLiteProBundle:Default:switchPublic, padid: 0 }
    
pad_deletePassword:
    pattern:    /pad/deletepass/{padid}
    defaults:   { _controller: HUBerlinEPLiteProBundle:Default:deletePassword, padid: 0 }